/** All ChatGPT DOM selectors live here. Fail closed if the UI changes. */
export const chatgptSelectors = Object.freeze({
  pickerTrigger: 'button[aria-haspopup="menu"], button[data-testid*="model"], button[aria-label*="model"], button[aria-label*="Thinking effort"]',
  picker: '[data-testid="composer-intelligence-picker-content"], [data-model-selection-view="true"]',
  modelToggle: '[role="menuitem"][aria-label="Select model"]',
  modelView: '[data-testid="composer-model-picker-slider-advanced-view"]',
  effortView: '[data-testid="composer-model-picker-slider-simple-view"]',
  modelOption: '[role="menuitemradio"]',
  modelName: '.truncate',
  effortSlider: '[data-model-reasoning-effort-slider]',
  sliderValue: '[role="slider"]',
  sliderTick: '[data-selected][data-locked]',
  effortLabel: '[data-max-effort]',
  composer: '#prompt-textarea[contenteditable="true"], textarea#prompt-textarea, form[data-type="unified-composer"] [contenteditable="true"], main [contenteditable="true"][role="textbox"]',
  send: 'button[data-testid="send-button"], button#composer-submit-button[aria-label="Send prompt"], button[type="submit"][aria-label="Send"], button[aria-label="Send prompt"], button[aria-label="Gửi lời nhắc"], button[aria-label="Send message"]',
  stop: 'button[data-testid="stop-button"], button[aria-label="Stop generating"], button[aria-label="Dừng tạo"]',
  signedOut: 'button[data-testid="login-button"], a[href="/auth/login"], button[data-testid="signup-button"]',
  user: '[data-message-author-role="user"]',
  assistant: '[data-message-author-role="assistant"]',
  assistantTurn: '[data-chatgpt-search-unit-key$=":assistant"], [data-content-search-unit-key$=":assistant"], [data-message-author-role="assistant"]',
  messages: '[data-message-author-role="user"], [data-message-author-role="assistant"]',
  turn: 'article[data-testid^="conversation-turn-"], [data-testid^="conversation-turn-"]',
  responseBody: '[data-markdown-text-style="assistant-message"], .markdown',
  turnActions: '.turn-action-controls',
  copyAction: 'button[aria-label="Copy"], button[data-testid="copy-turn-action-button"], button[aria-label="Copy response"], button[aria-label="Sao chép phản hồi"]',
  rateAction: 'button[aria-label="Rate response"]',
  shareAction: 'button[aria-label="Share"]',
  addToProjectAction: 'button[aria-label="Add to project sources"]',
  readAloudAction: 'button[aria-label="Read aloud"]',
  regenerateAction: 'button[aria-label="Regenerate response"]',
  moreActions: 'button[aria-label="More actions"]',
  completionAction: 'button[aria-label="Copy"], button[data-testid="copy-turn-action-button"], button[aria-label="Copy response"], button[aria-label="Sao chép phản hồi"]',
  streaming: '.result-streaming, [data-is-streaming="true"], [aria-busy="true"]',
  nonResponse: 'button, [role="button"], svg, style, script, [aria-hidden="true"]',
});
